language: c
compiler:
  - gcc
install:
  - sudo apt-get update || true
  - sudo apt-get install -y dpkg-dev debhelper python-all python3-all fakeroot python-setuptools python3-setuptools
before_script:
  - git fetch origin master:master
  - debian/rules make-orig-tar
script:
  - dpkg-buildpackage -tc -uc -us -i\\..*

