language: c
compiler:
  - gcc
install:
  - sudo apt-get install dpkg-dev debhelper python fakeroot
before_script:
  - git fetch origin master:master
  - debian/rules make-orig-tar
script:
  - dpkg-buildpackage -tc -uc -us -i\\..*

